root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "sqlc generate && go build -o ./tmp/main ./cmd/main.go"
  exclude_dir = ["tmp", "testdata", "logs", "downloads", "private"]
  exclude_regex = ["_test.go", "_gen.go"]
  include_ext = ["go", "toml", "yaml", "yml"]
  stop_on_error = false

[log]
  main_only = true
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true