name: sqlc vet
on:
  push:
    branches:
      - v2
  pull_request:

permissions:
  contents: read

jobs:
  sqlc:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.30.0'
      - run: sqlc vet